config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :plays do
    resources :reviews
  end

  root 'plays#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :plays
end

app/models/play.rb
class Play < ApplicationRecord
  belongs_to :user, dependent: :destroy
  belongs_to :category
  has_one_attached :photo
  has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :play
end

app/models/user.rb
class User < ApplicationRecord
  has_many :plays
  has_many :reviews, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/plays_controller.rb
class PlaysController < ApplicationController

  before_action :find_play, only: %i[show edit update destroy]

  def index
    @category = Category.find_by(name: params[:category])
    if params[:category].blank?
      @plays = Play.all.order('created_at DESC')
    else
        @play = Play.where(category_id: @category.id).order('created_at DESC')
    end
  end

  def new
    @play = current_user.plays.build
    @categories = Category.all.map{ |c| [c.name, c.id]}
  end

  def show
    @play = find_play
  end

  def create
    @play = current_user.plays.build(play_params)
    @play[:category_id] = params[:category_id]
    if @play.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @categories = Category.all.map{ |c| [c.name, c.id]}
  end

  def update
    @play[:category_id] = params[:category_id]
    if @play.update(play_params)
      redirect_to plays_path(@play)
    else
      render 'edit'
    end
  end

  def destroy
    redirect_to root_path if @play.destroy
  end


  private

  def play_params
    params.require(:play).permit(:title, :description, :director, :category_id, :photo)
  end

  def find_play
    @play = Play.find(params[:id])
  end



end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :find_play
  before_action :find_review, only: %i[edit update destroy]

  def new
    @review = Review.new
  end

  def create
        @review = Review.new(review_params)
        @review.play_id = @play.id
        @review.user_id = current_user.id

        if @review.save
          redirect_to plays_path(@play)
        else
          render 'new'
        end
  end

  def edit; end

  def update
    if @review.update(review_params)
      redirect_to play_path(@play)
    else
      render 'edit'
    end
  end

  def destroy
    @review.destroy
    redirect_to play_path(@play)
  end

  private

  def review_params
    params.require(:review).permit(:rating, :comment)
  end

  def find_play
    @play = Play.find(params[:play_id])
  end

  def find_review
    @review = Review.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plays_helper.rb
module PlaysHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_dropdown.html.erb
<div class="dropdown-container">
  <label for="openDropdown" class="dropdown">
    Dropdown
    <i class="fas fa-angle-down"></i>
  </label>

  <input type="checkbox" id="openDropdown" hidden>

  <div class="dropdown-menu">
    <span>Item 1</span>
    <span>Item 2</span>
    <span>Item 3</span>
    <span>Item 4</span>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Broadway</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <nav class="navbar navbar-default">
      <div class="navbar-header">
        <a href="/" class="navbar-brand">
          <%= render 'header/logo_svg' %>
        </a>
      </div>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in?  %>
          <li><%= link_to "sign Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign In", new_user_registration_path %></li>
          <li><%= link_to "Log In", new_user_session_path %></li>
        <% end %>
      </ul>

    <div class="dropdown-container">
      <label for="openDropdown" class="dropdown">
        sort
        <i class="fas fa-angle-down"></i>
      </label>

      <input type="checkbox" id="openDropdown" hidden>

      <div class="dropdown-menu">
        <% Category.all&.each do |category| %>
          <span className="<%= "active" if category.name == params[:category] %>">
            <%=link_to category.name, plays_path({category: category.name})%>
          </span>
        <% end %>
      </div>
    </div>


    <%#= render 'dropdown' %>

      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to "Add Play", new_play_path %></li>
        <%end %>
      </ul>
    </div>
  </nav>

  <div class="container">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
  </div>
  </body>
</html>

app/views/plays/_form.html.erb
<%= simple_form_for @play do |f| %>
  <%= select_tag(:category_id, options_for_select(@categories), {
      :prompt =>"Select Category"
  }) %>
  <%= f.file_field :photo %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :director %>
  <%= f.button :submit %>
<% end %>

app/views/plays/edit.html.erb
<h4>Edit BroadWay Play</h4>

<%= simple_form_for @play do |f| %>
  <%= f.file_field :photo %>
  <%= f.select(:category_id, @categories) %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :director %>
  <%= f.button :submit %>
<% end %>

app/views/plays/index.html.erb
<h1 class="current-category">
  <%=params[:category] %>
</h1>

<% if @plays.nil? || @plays.count ==  0 %>

  <h3><%= "There are no plays tagged #{params[:category]}" %></h3>
<% else %>
  <%  @plays.each do |play| %>
    <div class="col-md-3">
      <a href="/plays/<%= play.id %>">
        <%= image_tag(play.photo, width: 200, class: 'play') if play.photo.attached? %>
      </a>
    </div>
  <% end %>
<% end %>

app/views/plays/new.html.erb
<h1 class="new">New BroadWay Play</h1>

<%= render 'form' %>

app/views/plays/show.html.erb
<div class="row">

  <div class="col-md-4">
    <%= image_tag(@play.photo, width: 200, class: 'play-show') if @play.photo.attached? %>
  </div>

  <div class="col-md-8">
    <div class="play-info">
      <h2 class="play-title"> <%=@play.title %> </h2>
      <h3 class="play-director"><span>From </span> <%=@play.director %> </h3>
      <% unless @play.category.nil? %>
        <h4 class="">
          <%=  @play.category.name %>
        </h4>
      <%end %>
      <p class="play-desc"> <%=@play.description %> </p>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="reviews">
      <h1>Reviews</h1>
      <%= render @play.reviews %>
      <div>
        <%= link_to 'Add Reviews', new_play_review_path(@play), class: 'btn-custom' %>
      </div>
    </div>
  </div>
</div>


<div class="links btn-groups">
  <% if user_signed_in? %>
    <% if @play.user_id == current_user.id %>
        <%= link_to  "edit", edit_play_path(@play), class: "btn btn-custom" %>
        <%= link_to  "delete", play_path(@play), method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-custom"%>
    <%end %>
  <%end %>
  <%= link_to  "back", root_path%>
</div>

app/views/reviews/_form.html.erb
<%= simple_form_for([@play, @play.reviews.build]) do |f| %>
  <div id="rating-form">
    <label> Rating</label>
  </div>
  <%= f.input :comment  %>
  <%= f.button :submit, class: 'btn-custom2' %>
<%end %>

<script>
  $('#rating-form').raty({
      path: '/assets/',
      scoreName: 'review[rating]'
  })
</script>

app/views/reviews/_review.html.erb
<div class="review">
  <div class="review-rating"> data-score="<%= review.rating %>"</div>
  <p class="review-comment"><%= review.comment %></p>
  <%if user_signed_in? %>
    <% if review.user_id == current_user.id %>
      <div class="link btn-group">
        <%= link_to "Edit", edit_play_review_path(review.play, review), class: "btn btn-custom"%>
        <%= link_to "Delete",play_review_path(review.play, review), method: :delete, data: {confirm: "Are you sure?"}, class:"btn btn-custom" %>
      </div>
    <%end %>
  <%end %>
</div>

<script>
  $('.review-rating').raty({
      readOnly: true,
      score: function() {
          return $(this).attr('data-score')
      },
      path: '/assets/'
  });
</script>

app/views/reviews/edit.html.erb
<div class="col-md-10 col-md-offset-1">
  <div class="edit-review-form">
    <h1> Edit Review</h1>
    <%= simple_form_for([@play, @review]) do |f| %>
      <div id="rating-form">
        <label> Rating </label>
      </div>
      <%= f.input :comment  %>
      <%= f.button :submit, class: 'btn-custom2' %>
    <%end %>
  </div>
</div>

<script>
    $('#rating-form').raty({
        path: '/assets/',
        scoreName: 'review[rating]'
    })
</script>

app/views/reviews/new.html.erb
<div class="col-md-10 col-md-offset-1">
  <div class="new-review-form">
    <h1>Post Review</h1>
    <%= render 'form' %>
  </div>
</div>